name: 'Build and release'

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository ğŸ‰
        uses: actions/checkout@v4
      - name: Setup node env ğŸ“¦
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          check-latest: true
          cache: 'npm'
      - name: Install dependencies ğŸš€
        run: npm ci --prefer-offline --no-audit

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository âœ¨
        uses: actions/checkout@v4
      - name: Setup node env ğŸ“¦
        uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com/
          node-version-file: .nvmrc
          check-latest: true
          cache: 'npm'
      - name: Install dependencies ğŸš€
        run: npm ci --prefer-offline --no-audit
      - name: Run build ğŸ
        run: npm run build
      - name: Create compressed tarball file ğŸ“¦
        run: npm pack
      - name: Publish to GitHub Packages ğŸš€
        run: npm publish --access=public *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release package ğŸ“¦
        uses: actions/upload-artifact@v4
        with:
          name: release-package
          path: ./*.tgz
